# fly.toml app configuration file generated for kbbi-bot on 2023-09-26T20:39:14+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kbbi-bot"
primary_region = "sin"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
