# fly.toml app configuration file generated for kbbi-bot-v2 on 2023-05-12T12:59:18+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kbbi-bot-v2"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
builder = "heroku/buildpacks:20"

[env]
NODE_ENV = "production"
PORT = "8080"

[experimental]
auto_rollback = true
cmd = ["node ./dist/app.js"]

[[services]]
internal_port = 8080
min_machines_running = 0
processes = ["app"]
protocol = "tcp"
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
