# fly.toml app configuration file generated for kbbi-bot-v3 on 2023-09-26T19:48:53+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kbbi-bot-v3"
primary_region = "sin"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
